const PRODUCTS = [
  {
    id: 'iphone-16-pro',
    name: 'iPhone 16 Pro 256 GB',
    price: 1099.0,
    description:
      'Pro-grade titanium flagship with the A18 Pro chip, the new Camera Control button, and a brighter, more efficient ProMotion display.',
    image: 'assets/images/products/iphone-16-pro/white-titanium.jpg',
    badge: 'New',
    colors: [
      {
        id: 'white-titanium',
        name: 'White Titanium',
        hex: '#f4f1eb',
        image: 'assets/images/products/iphone-16-pro/white-titanium.jpg',
      },
      {
        id: 'black-titanium',
        name: 'Black Titanium',
        hex: '#3c3a37',
        image: 'assets/images/products/iphone-16-pro/black-titanium.jpg',
      },
      {
        id: 'natural-titanium',
        name: 'Natural Titanium',
        hex: '#c9c0b6',
        image: 'assets/images/products/iphone-16-pro/natural-titanium.jpg',
      },
      {
        id: 'desert-titanium',
        name: 'Desert Titanium',
        hex: '#a98b6a',
        image: 'assets/images/products/iphone-16-pro/desert-titanium.jpg',
      },
    ],
    specs: [
      { label: 'Display', value: '6.3" Super Retina XDR OLED, 120 Hz ProMotion' },
      { label: 'Chip', value: 'Apple A18 Pro (3 nm, 6-core CPU, 6-core GPU)' },
      {
        label: 'Camera',
        value: '48 MP Fusion main + 48 MP Ultra Wide + 12 MP 5x Telephoto',
      },
      { label: 'Front camera', value: '12 MP TrueDepth, ƒ/1.9' },
      { label: 'Battery', value: 'Up to 27 h video playback' },
      { label: 'Storage', value: '256 GB' },
      { label: 'Weight', value: '199 g' },
      { label: 'Connectivity', value: 'USB-C (USB 3), Wi-Fi 7, 5G, Bluetooth 5.3' },
    ],
  },
  {
    id: 'macbook-pro-m4',
    name: 'MacBook Pro 14" M4',
    price: 1599.0,
    description:
      'Apple M4 with a 10-core CPU and a 10-core GPU, a 14.2" Liquid Retina XDR display, and up to 24 hours of battery — quietly built for serious work.',
    image: 'assets/images/products/macbook-pro-m4/space-black.jpg',
    badge: 'New',
    colors: [
      {
        id: 'space-black',
        name: 'Space Black',
        hex: '#2a2a2c',
        image: 'assets/images/products/macbook-pro-m4/space-black.jpg',
      },
      {
        id: 'silver',
        name: 'Silver',
        hex: '#d9d9d9',
        image: 'assets/images/products/macbook-pro-m4/silver.jpg',
      },
    ],
    specs: [
      { label: 'Display', value: '14.2" Liquid Retina XDR, 1000 nits sustained / 1600 peak' },
      { label: 'Chip', value: 'Apple M4 (10-core CPU, 10-core GPU, 16-core Neural Engine)' },
      { label: 'Memory', value: '16 GB unified memory' },
      { label: 'Storage', value: '512 GB SSD' },
      { label: 'Battery', value: 'Up to 24 hours' },
      { label: 'Ports', value: '3× Thunderbolt 4, HDMI, SDXC, MagSafe 3, headphone jack' },
      { label: 'Camera', value: '12 MP Center Stage' },
      { label: 'Weight', value: '1.55 kg' },
    ],
  },
  {
    id: 'ipad-pro-m4',
    name: 'iPad Pro 11" M4',
    price: 999.0,
    description:
      'The thinnest Apple product ever (5.3 mm) with a tandem-OLED display, M4 chip, and Apple Pencil Pro support — a portable creative studio.',
    image: 'assets/images/products/ipad-pro-m4/space-black.jpg',
    badge: '',
    colors: [
      {
        id: 'space-black',
        name: 'Space Black',
        hex: '#2a2a2c',
        image: 'assets/images/products/ipad-pro-m4/space-black.jpg',
      },
      {
        id: 'silver',
        name: 'Silver',
        hex: '#d9d9d9',
        image: 'assets/images/products/ipad-pro-m4/silver.jpg',
      },
    ],
    specs: [
      { label: 'Display', value: '11" Ultra Retina XDR Tandem OLED, 120 Hz ProMotion' },
      { label: 'Chip', value: 'Apple M4 (9-core CPU, 10-core GPU, 16-core Neural Engine)' },
      { label: 'Memory', value: '8 GB unified memory' },
      { label: 'Storage', value: '256 GB' },
      { label: 'Camera', value: '12 MP Wide rear + 12 MP Ultra Wide landscape front' },
      { label: 'Pencil', value: 'Works with Apple Pencil Pro and Apple Pencil (USB-C)' },
      { label: 'Connectivity', value: 'Wi-Fi 6E, Bluetooth 5.3, USB-C (Thunderbolt / USB 4)' },
      { label: 'Thickness', value: '5.3 mm — thinnest Apple product ever' },
    ],
  },
  {
    id: 'apple-watch-ultra-2',
    name: 'Apple Watch Ultra 2',
    price: 799.0,
    description:
      '49 mm aerospace-grade titanium watch built for the outdoors, with a 3000-nit display, dual-frequency GPS, and 36-hour battery life.',
    image: 'assets/images/products/apple-watch-ultra-2/blue-alpine.jpg',
    badge: 'Popular',
    colors: [
      {
        id: 'blue-alpine',
        name: 'Blue Alpine Loop',
        hex: '#3a4a78',
        image: 'assets/images/products/apple-watch-ultra-2/blue-alpine.jpg',
      },
      {
        id: 'orange-ocean',
        name: 'Orange Ocean Band',
        hex: '#e8732d',
        image: 'assets/images/products/apple-watch-ultra-2/orange-ocean.jpg',
      },
    ],
    specs: [
      { label: 'Case', value: '49 mm aerospace-grade titanium' },
      { label: 'Display', value: 'Always-On Retina, 3000 nits peak brightness' },
      { label: 'Chip', value: 'Apple S9 SiP with 4-core Neural Engine' },
      { label: 'Battery', value: 'Up to 36 hours (72 hours Low Power)' },
      { label: 'Water resistance', value: '100 m / WR100, EN13319 dive-spec to 40 m' },
      { label: 'GPS', value: 'Precision dual-frequency L1 + L5' },
      { label: 'Sensors', value: 'ECG, blood oxygen, temperature, depth, siren' },
      { label: 'Connectivity', value: 'GPS + Cellular, Wi-Fi, Bluetooth 5.3' },
    ],
  },
  {
    id: 'airpods-pro-2',
    name: 'AirPods Pro 2 (USB-C)',
    price: 249.0,
    description:
      'Active Noise Cancellation, Adaptive Audio, Personalized Spatial Audio, and a MagSafe USB-C charging case with a built-in speaker.',
    image: 'assets/images/products/airpods-pro-2/white.jpg',
    badge: '',
    colors: [
      {
        id: 'white',
        name: 'White',
        hex: '#ffffff',
        image: 'assets/images/products/airpods-pro-2/white.jpg',
      },
    ],
    specs: [
      { label: 'Chip', value: 'Apple H2' },
      { label: 'Active Noise Cancellation', value: 'Up to 2× more than first gen' },
      { label: 'Spatial Audio', value: 'Personalised, with dynamic head tracking' },
      { label: 'Battery', value: 'Up to 6 h listening per charge / 30 h with case' },
      { label: 'Case', value: 'MagSafe + USB-C, IP54, built-in speaker' },
      { label: 'Sensors', value: 'Skin-detect, force, optical, motion, accelerometer' },
      { label: 'Hearing health', value: 'Hearing test, hearing aid (clinical-grade), loud-sound reduction' },
    ],
  },
  {
    id: 'sony-wh-1000xm5',
    name: 'Sony WH-1000XM5',
    price: 399.0,
    description:
      'Industry-leading wireless noise cancellation, eight microphones for crystal-clear voice calls, 30-hour battery, and ultra-soft synthetic leather earpads.',
    image: 'assets/images/products/sony-wh-1000xm5/black.jpg',
    badge: 'Bestseller',
    colors: [
      {
        id: 'black',
        name: 'Black',
        hex: '#1a1a1a',
        image: 'assets/images/products/sony-wh-1000xm5/black.jpg',
      },
    ],
    specs: [
      { label: 'Drivers', value: '30 mm carbon-fibre composite' },
      { label: 'ANC', value: 'Dual Noise Sensor with Auto NC Optimizer, 8 microphones' },
      { label: 'Battery', value: '30 h with ANC on, 3 min charge → 3 h playback' },
      { label: 'Codecs', value: 'LDAC, AAC, SBC, Hi-Res Audio Wireless' },
      { label: 'Calls', value: 'Precise Voice Pickup with 4 beamforming mics' },
      { label: 'Multipoint', value: 'Yes (two devices simultaneously)' },
      { label: 'Weight', value: '250 g' },
    ],
  },
  {
    id: 'sony-a7-iv',
    name: 'Sony α7 IV (body)',
    price: 2499.0,
    description:
      '33 MP full-frame Exmor R sensor, 4K 60p 10-bit video, real-time eye AF for humans, animals and birds, and a fully articulating touchscreen.',
    image: 'assets/images/products/sony-a7-iv/black.jpg',
    badge: '',
    colors: [
      {
        id: 'black',
        name: 'Black',
        hex: '#1a1a1a',
        image: 'assets/images/products/sony-a7-iv/black.jpg',
      },
    ],
    specs: [
      { label: 'Sensor', value: '33 MP back-illuminated full-frame Exmor R CMOS' },
      { label: 'Processor', value: 'BIONZ XR' },
      { label: 'Video', value: '4K 60p 10-bit 4:2:2, S-Cinetone, S-Log3' },
      { label: 'AF', value: 'Real-time Eye AF (humans, animals, birds)' },
      { label: 'Burst', value: 'Up to 10 fps with continuous AF/AE' },
      { label: 'Stabilisation', value: '5-axis IBIS, up to 5.5 stops' },
      { label: 'Display', value: '3.0" vari-angle touchscreen, 0.5" 3.69 M-dot OLED EVF' },
      { label: 'Storage', value: 'Dual slot: 1× CFexpress Type A / SD UHS-II + 1× SD UHS-II' },
    ],
  },
  {
    id: 'jbl-flip-6',
    name: 'JBL Flip 6',
    price: 129.0,
    description:
      'Bold sound and powerful bass in a compact, IP67 dust- and waterproof speaker. 12 hours of battery and PartyBoost for stereo or party-mode pairing.',
    image: 'assets/images/products/jbl-flip-6/black.jpg',
    badge: 'Sale',
    colors: [
      {
        id: 'black',
        name: 'Black',
        hex: '#1a1a1a',
        image: 'assets/images/products/jbl-flip-6/black.jpg',
      },
      {
        id: 'blue',
        name: 'Blue',
        hex: '#1d6bb1',
        image: 'assets/images/products/jbl-flip-6/blue.jpg',
      },
    ],
    specs: [
      { label: 'Output', value: '20 W RMS racetrack woofer + 10 W RMS tweeter' },
      { label: 'Bluetooth', value: '5.1, range up to 10 m' },
      { label: 'Battery', value: '4 800 mAh — up to 12 hours' },
      { label: 'Charging', value: 'USB-C, ≈ 2.5 h full charge' },
      { label: 'Durability', value: 'IP67 dust- and waterproof' },
      { label: 'Multi-speaker', value: 'JBL PartyBoost (stereo or party mode)' },
      { label: 'Weight', value: '550 g' },
    ],
  },
];
